### ISSUE TITLE
Convert views to use Class Based Views

### ISSUE THREAD

**Issue by jeanmask** [nitely/Spirit#135]
Convert views to use Class Based Views to improve lib 
extensibility.

**Comment by nitely** [comment]
I'm against CBVs. There are other, better ways to make a system extensible, usually through plugins.

I won't elaborate much on this, I'll just say providing CBVs public APIs would be a maintenance nightmare, I'd have to keep backward compatibility everywhere and that's just not realistic. Not to mention that would only work for forks, not for the community as a whole, since that does not magically allow the creation of plugins (ie: extensions will break other extensions), and if you are forking you may as well just modify the FBVs.

There are some ongoing efforts to make Spirit extensible, see [django-hooks](https://github.com/nitely/django-hooks)
