### ISSUE TITLE
LastIPMiddleware sql update error because REMOTE_ADDR is "b''"

### ISSUE THREAD

**Issue by cryptogun** [nitely/Spirit#150]
REMOTE_ADDR is "b''" when login from LAN and DEBUG=True. If I set DEBUG=False everything works great.
I think here's the target code: [XForwardedForMiddleware](https://github.com/nitely/Spirit/blob/c476fe06aa28d4656369e8d85a43e4451a9005ff/spirit/core/middleware.py#L13-L14), [LastIPMiddleware](https://github.com/nitely/Spirit/blob/c476fe06aa28d4656369e8d85a43e4451a9005ff/spirit/user/middleware.py#L45). Can we remove [this](https://github.com/nitely/Spirit/blob/c476fe06aa28d4656369e8d85a43e4451a9005ff/spirit/core/middleware.py#L13) line?
Error details:
```
DataError at /
invalid input syntax for type inet: "b''"
LINE 1: UPDATE "spirit_user_userprofile" SET "last_ip" = 'b'''''::in...
```
```
▶ Local vars
Variable	Value
params  (Inet("b''"), 1)
self   <django.db.backends.utils.CursorDebugWrapper object at 0x7f8d2aa436d8>
sql   ('UPDATE "spirit_user_userprofile" SET "last_ip" = %s WHERE '
 '"spirit_user_userprofile"."user_id" = %s')
```
Meta:
```
HTTP_X_FORWARDED_FOR  '192.168.1.4'
HTTP_X_FORWARDED_PROTO  'http'
HTTP_X_REAL_IP  '192.168.1.4'
REMOTE_ADDR  "b''"
```
Great app. Though there's no link to `st/admin/comment/flag/` from `st/admin/`

**Comment by nitely** [comment]
That middleware is commented out (`XForwardedForMiddleware`) and should probably be removed, since it's there for those behind a reverse proxy (i.e: nginx).

But it seems like a bug elsewhere. What Django and Python version is this? are you just running `$ python manage.py runsever`?

> Though there's no link to st/admin/comment/flag/ from st/admin/

There is a menu option called `Flags` that takes you there. Go to `st/admin/` and click `show menu`.

**Comment by cryptogun** [comment]
I uncommented it cause I thought it's me who committed it out when I did the merge :P
Now I remove `XForwardedForMiddleware` and set DEBUG=True, and then the problem still exists. `REMOTE_ADDR == 'b""'`. Wait for me to find out what changes the value from `""` into `'b""'`
I use Nginx and Gunicorn with systemd, so do I need `XForwardedForMiddleware`?
Python 3.5.2
Django 1.10.3
nginx version: nginx/1.10.0 (Ubuntu)
Gunicorn 19.6.0

Oh, Now I see. It is named "标记" (mark) on `st/admin/`, while it is named "举报" (report) under posts. I think the latter translation is more accurate. I found `st/admin/comment/flag/` from `urls.py`

**Comment by nitely** [comment]
I see. It's likely a bug in gunicorn, AFAIK WSIG specifies the values should be all unicode/str not bytestrings (`b''`). I'll issue a workaround though.

> I use Nginx and Gunicorn with systemd, so do I need XForwardedForMiddleware?

Yep, but you also have to set `HTTP_X_FORWARDED_FOR`. This is only if you want to log user IPs, otherwise is not strictly required.

`X_FORWARDED_FOR` is an HTTP header that reverse proxies (such as Nginx when proxying) will use to *append or preppend* the user IP. The thing is, if the user sets this header manually, then Nginx will append the real user IP to that value. Some proxies will append the real IP, some other will preppend it, that's why that middleware was removed from Django (Django use to ship it), there is no general way to know whether the proxy is appending or preppending, leading to IP spoofing.

This is a common nginx config

```
server {

// ... lines removed for brevity

                location / {				
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Host $http_host;
			proxy_redirect off;
			proxy_pass http://127.0.0.1:8888;
		}

}
```

> Oh, Now I see. It is named "标记" (mark) on st/admin/, while it is named "举报" (report) under posts. I think the latter translation is more accurate. I found st/admin/comment/flag/ from urls.py

If you care to fix that, join the Spirit translator team https://www.transifex.com/projects/p/spirit/ I will make sure to accept the join request :smile_cat:

**Comment by cryptogun** [comment]
OK, thanks for your information.

**Comment by nitely** [comment]
> Yep, but you also have to set HTTP_X_FORWARDED_FOR. This is only if you want to log user IPs, otherwise is not strictly required.

I'll correct myself. It's kinda required. IPs are needed to rate-limit user logging attempts, if not set properly then they all share the same rate-limit key, which makes them all share the same quota.

**Comment by bastien34** [comment]
Finally, what is the solution to this issue? Is it related to Nginx conf?

Here is my site conf file that used to work fine:

    (...)
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://unix:/tmp/mf.sock:/uri/;
        proxy_redirect off;
        }

I also removed the middleware `XForwardedForMiddleware` and DEBUG is set to True.

**Comment by cryptogun** [comment]
@bastien34 My local solution is to remove [this line](https://github.com/nitely/Spirit/blob/c476fe06aa28d4656369e8d85a43e4451a9005ff/spirit/core/middleware.py#L13). In production `DEBUG=False` so this error won't occur.
It's better for me to record IP. So I enabled `XForwardedForMiddleware` in my settings (spirit comment it out by default). If I include [that line](https://github.com/nitely/Spirit/blob/c476fe06aa28d4656369e8d85a43e4451a9005ff/spirit/core/middleware.py#L13), same error occurs, just tested.
@nitely I think we should remove that line to set `request.META['REMOTE_ADDR']` if `DEBUG=True`.
If leaking LAN IP is a concern, we can filter that.
If nginx return b'', we can catch that exception and return str('')

**Comment by nitely** [comment]
@cryptogun yep, we should remove that conditional statement. It's better to behave the same way regardless of DEBUG setting.

**Comment by bastien34** [comment]
Thanks for your answer but my issue come from the user/middleware.py and specially the lastIPMiddleware. I'm checking that.

**Comment by nitely** [comment]
`XForwardedForMiddleware` should run before `LastIPMiddleware` and set the `REMOTE_ADDR`, then the issue should be gone. You can add your own `XForwardedForMiddleware` if you don't want to wait for a fix. It should be exactly the same middleware but without the conditional statement.

**Comment by bastien34** [comment]
I got it ! Thanks!
