### ISSUE TITLE
Label of user/comment form is not translated.

### ISSUE THREAD

**Issue by cryptogun** [nitely/Spirit#155]
1. `Comment`
2. `Users`
URL: `topic/private/publish/2/` `topic/publish/`
Adding `label=_('blah blah')` to Form field should fix this.
Target code: [comment](https://github.com/nitely/Spirit/blob/master/spirit/topic/private/forms.py#L67), [user](https://github.com/nitely/Spirit/blob/master/spirit/comment/forms.py#L21).

**Comment by cryptogun** [comment]
3. If two .po files have the same msgid, only one translation will be used. So:
`st/admin/topic/closed`: `Closed` translated to "关闭的"(closed).
`st/admin/comment/flag/opened/`: `Closed` also translated "关闭的"(closed), even if you set the translation to other words(e.g. handled/moderated) in .po .
Solution: change one of the `msgid "Closed"` to other id such as `msgid "Closed2"`
```
spirit/topic/admin/locale/zh_Hans/LC_MESSAGES/django.po:
   23  #: templates/spirit/topic/admin/_tabs.html:5
   24  msgid "Closed"
   25: msgstr "关闭的"

spirit/comment/flag/admin/locale/zh_Hans/LC_MESSAGES/django.po:
   27  #: templates/spirit/comment/flag/admin/_tabs.html:5
   28  msgid "Closed"
   29: msgstr "已处理"
```
4. `st/admin/comment/flag/1/` `Is closed:` not translated. Adding
`    is_closed = forms.BooleanField(label=_'Is closed')` to [this form](https://github.com/nitely/Spirit/blob/master/spirit/comment/flag/admin/forms.py#L11) should work (and modify .po).

**Comment by nitely** [comment]
> 1. Comment
> 2. Users
> URL: topic/private/publish/2/ topic/publish/
> Adding label=_('blah blah') to Form field should fix this.
> Target code: comment, user.
> 4. st/admin/comment/flag/1/ Is closed: not translated. Adding
is_closed = forms.BooleanField(label=_'Is closed') to this form should work (and modify .po).

Thanks for reporting this. PRs are welcome, btw. In case you want to fix this.

> 3. Solution: change one of the msgid "Closed" to other id such as msgid "Closed2"

I don't think that would be a good solution. Mostly coz no translator will know they have to actually translate "Closed2" to "Closed" (in their language), instead of "Closed2" (i.e I may translate "Closed2" as "Cerrado2" in spanish). I don't think I've ever seen a project that handles locales that way.

I would agree on replacing "Closed" by "Moderated" (for flags) if you think it's more meaningful.
