### ISSUE TITLE
Best way programmatically add Topic and Comment?

### ISSUE THREAD

**Issue by t4r7s** [nitely/Spirit#227]
Does Spirit have API or something like that? What is the best way programmatically add Topic and Comment?

**Comment by nitely** [comment]
Nop, it does not. I made a command[0] for this a while back but it does not increment the topic's comments-count, sends notifications, etc. Otherwise, you could use `RequestFactory` from `django.test` and just pass it to the view you want (publish topic or publish comment).

[0] https://github.com/nitely/Spirit/blob/feature/command_fake_data/spirit/core/management/commands/spiritcreatefakedata.py

**Comment by t4r7s** [comment]
Thank you for answer!

**Comment by nitely** [comment]
NP!
