### ISSUE TITLE
Modify the username of the default display？

### ISSUE THREAD

**Issue by jiangsi520** [nitely/Spirit#235]
From a security point of view, it is not safe to display the user name of the administrator. How do I modify the username here?
![default](https://user-images.githubusercontent.com/30169495/42806059-1fb4f500-89e0-11e8-9d7f-678333dbf047.png)

**Comment by nitely** [comment]
Not sure why did you change the original comment, but issue is `magic` dependency must be installed by running `pip install django-spirit[files]` when file uploading is enabled, there should have been an error logged about it.

About the user profile picture, Spirit only supports [gravatar](https://en.gravatar.com/) at the moment :cry:

**Comment by jiangsi520** [comment]
The problem of uploading files has been solved before. Thank you for your answer.

**Comment by nitely** [comment]
Security by obscurity is the worst form of security. Hiding the username is not enough, an attacker can guess the user id number 1 is the administrator. Also, the username is shown when you mention someone, in the profile URL, an in many other places. Spirit has a login rate-limit, so as along as the password is strong you should be fine. But, if you are really concern about security, then just disallow administrator login by password and add login by sending a login link to email, you'll have to implement that yourself, though (PRs are welcome :smile_cat: ).

P.S: Please, stop changing the issue topic. Next time close it and open a new one, otherwise I'll refuse answering any other of your issues.
