### ISSUE TITLE
Test: no such table: spirit_autoslugmodel

### ISSUE THREAD

**Issue by uzi200** [nitely/Spirit#37]
When I run the django test i got that the table for `autoslugmodel` does not exist in the db, I already found in Travis CI that you have this issue in this [build](https://travis-ci.org/nitely/Spirit/builds/36529119 ) and  you fix it  with a  deconstructor function, so I pull the commits into my repo but the issue persists. Any suggestions ?

**Comment by nitely** [comment]
Hi!, that issue was fixed [here](https://github.com/nitely/Spirit/commit/891b4d0799f30f30c3d9e4aec897dc7bdb8ee2b4), there was a migration missing (autoSlugField).

Try the [future branch](https://github.com/nitely/Spirit/tree/future), it should work, also read [this](https://github.com/nitely/Spirit/tree/future/example).

The next Spirit release is around the corner (a week or so). I'd wait, if I were you.

**Comment by nitely** [comment]
I merged `future` into `master`. Not an official release, but it's close enough.

Closing this.
