### ISSUE TITLE
Unread comments count for each topic

### ISSUE THREAD

**Issue by alesdotio** [nitely/Spirit#70]
After a quick look at the code would it be possible to use the CommentBookmark to find out how many unread comments are there for each topic? Do you think it would make sense to show this number next to the total number of comments?

**Comment by nitely** [comment]
No, It wouldn't... and it wouldn't be efficient.

> Do you think it would make sense to show this number next to the total number of comments?

I'm not sure. I'm mean, if someone is interested in a topic, she should be subscribed to it, and then she will receive a notification showing how many people has commented on that topic since the last read.

The notification system does not have that feature yet, I'm writing a notification app right now to address this as well as other use cases, like showing notifications that are not related to topics (ie: badges, followers, etc).

**Comment by alesdotio** [comment]
Isn't the unread count just Topic.comment_count - CommentBookmark.comment_number?

**Comment by nitely** [comment]
I take it back, it would be possible. Still, not efficient at all.

A much better approach would be to store a counter in the TopicUnread model. Either way, I'm not sure I want to show this information.

I'm leaving this open as I may change my mind in the future.

**Comment by alesdotio** [comment]
Why do you say it's inefficient? As far as I can tell, CommentBookmark is prefetched in [Topic.objects.with_bookmarks()](https://github.com/nitely/Spirit/blob/master/spirit/topic/views.py#L127) so there would be no additional query necessary.

**Comment by nitely** [comment]
Oh! Actually I was saying that coz I didn't realize the comment count is being stored in `comment_count`, I was thinking in something like `topic.comment_set.count`, sorry.

Then I take that back too. It'd be ok. Still don't know if I want to show that info :smile: 
May be showing it on the topics unread list would be ok.
